sonar.projectKey=OlegRakhilov_github_python-project-52
sonar.organization=OlegRakhilov_github
sonar.host.url=https://sonarcloud.io

# Пути к исходному коду
sonar.sources=task_manager
sonar.python.version=3.13

# Исключения (миграции и тесты не анализируем на дубликаты)
sonar.exclusions=**/migrations/**, **/tests.py