# Generated by Django 6.0.2 on 2026-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Name"
            ),
        ),
    ]
